AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local test version of the notification microservice.

Resources:

    AdminService:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs8.10
            Timeout: 300
            Environment:
                Variables:
                    SETTINGS_TBL: TMP
                    LOGGING_LEVEL: TMP
            Events:
                SendNotification:
                    Type: Api
                    Properties:
                        Path: /notify
                        Method: ANY
