AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local test version of the event microservice.

Resources:

    EventService:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs10.x
            Timeout: 300
            Environment:
                Variables:
                    IDP: TMP
                    LOGGING_LEVEL: TMP
                    EVENTS_TBL: TMP
                    REGISTRATION_TBL: TMP
            Events:
                GetEvents:
                    Type: Api
                    Properties:
                        Path: /devices/{deviceId}/events
                        Method: ANY
                GetEvent:
                    Type: Api
                    Properties:
                        Path: /devices/{deviceId}/events/{eventId}
                        Method: ANY
                GetEventHistory:
                    Type: Api
                    Properties:
                        Path: /devices/events
                        Method: ANY
                GetAlerts:
                    Type: Api
                    Properties:
                        Path: /devices/alerts
                        Method: ANY
